import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
export default function Home() {
	const handleOnBannerBtnClick = () => {
		console.log("banner button");
	};
	// console.log("styles", styles);
	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta
					name="Find coffee stores near you"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText="View stores nearby"
					handleOnClick={handleOnBannerBtnClick}
				/>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
